plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ms'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	//mapstruct
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	//google
	implementation 'com.google.cloud:google-cloud-storage:2.69.0'
	implementation 'com.google.cloud:google-cloud-secretmanager:2.94.0'
	implementation 'com.google.apis:google-api-services-gmail:v1-rev20240520-2.0.0'
	implementation 'com.google.auth:google-auth-library-oauth2-http:1.49.0'
	implementation 'org.eclipse.angus:angus-mail:2.0.3'
	//paseto
	implementation 'io.github.nbaars:paseto4j-version4:2024.3'
	//jackson
	// Jackson datatype for Java 8 Date/Time support
	implementation 'tools.jackson.datatype:jackson-datatype-hibernate7:3.0.3'

}

tasks.named('test') {
	useJUnitPlatform()
}
