spring:
  profiles:
    active: prod
  application:
    name: chitcircle

gcp:
  project-id: chitcircle-prod
  region: asia-south1
  storage:
    image-upload-bucket: chitcircle-image-uploads
    receipt-upload-bucket: chitcircle-image-uploads
    object-key-prefix: ""
  secrets:
    database: db-credentials
    hikari: hikari
    paseto: paseto
