spring:
  profiles:
    active: prod
  application:
    name: chitcircle

gcp:
  project-id: chitcircle-prod
  region: asia-south1
  storage:
    image-upload-bucket: chitcircle-image-uploads
    receipt-upload-bucket: chitcircle-image-uploads
    kyc-upload-bucket: chitcircle-kyc-documents
    object-key-prefix: ""
  secrets:
    database: db-credentials
    hikari: hikari
    paseto: paseto
    gmail-oauth: gmail-oauth
  email:
    sender: sreekeerthimaripally@gmail.com
    enabled: true
